<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Reports</title>
</head>
<body>
    <h1>Manage Reports</h1>

    <h2>Generate New Report</h2>
    <form action="<?= base_url('/report/store') ?>" method="post">
        <?= csrf_field() ?>
        <label for="report_type">Report Type:</label>
        <select name="report_type" id="report_type" required>
            <option value="">-- Select --</option>
            <option value="patient">Patient</option>
            <option value="consultation">Consultation</option>
            <option value="appointment">Appointment</option>
            <option value="inventory">Inventory</option>
            <option value="announcement">Announcement</option>
            <option value="comprehensive">Comprehensive (All Data)</option>
        </select>
      
        <button type="submit">Generate</button>
    </form>

    <h2>List of Reports</h2>

    <form id="bulkDeleteForm" action="<?= base_url('/report/bulk-delete') ?>" method="post">
        <?= csrf_field() ?>
        
        <div style="margin-bottom: 10px;">
            <button type="button" id="selectAllBtn" style="padding: 8px 12px; margin-right: 5px;">Select All</button>
            <button type="button" id="deselectAllBtn" style="padding: 8px 12px; margin-right: 5px;">Deselect All</button>
            <button type="submit" id="bulkDeleteBtn" style="padding: 8px 12px; background-color: #dc3545; color: white; cursor: pointer;" disabled>Delete Selected</button>
        </div>

        <table border='1'>
            <tr>
                <th style="width: 50px;">
                    <input type="checkbox" id="masterCheckbox" onchange="toggleAllCheckboxes(this)">
                </th>
                <th>Report ID</th>
                <th>Report Type</th>
                <th>Generated By</th>
                <th>Generated Date</th>
                <th>Actions</th>
            </tr>

            <?php if(!empty($report)): ?>

                <?php foreach($report as $r): ?>

                    <tr>
                        <td style="text-align: center;">
                            <input type="checkbox" class="reportCheckbox" name="report_ids[]" value="<?= esc($r['report_id']) ?>" onchange="updateDeleteButton()">
                        </td>
                        <td><?= esc($r['report_id']) ?></td>
                        <td><?= esc(ucfirst($r['report_type'])) ?></td>
                        <td><?= esc($r['generated_by']) ?></td>
                        <td><?= esc($r['generated_at']) ?></td>

                        <td>
                            <a href="<?= base_url('/report/view/'.$r['report_id'])?>">View</a>
                            <a href="<?= base_url('/report/delete/'.$r['report_id'])?>" onclick="return confirm('Are you sure to delete report #<?= esc($r['report_id']) ?>?')">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>

            <?php else: ?>
                <tr>
                    <td colspan="6">No Reports</td>
                </tr>
            <?php endif; ?>

        </table>
    </form>

    <script>
        function toggleAllCheckboxes(masterCheckbox) {
            const checkboxes = document.querySelectorAll('.reportCheckbox');
            checkboxes.forEach(checkbox => {
                checkbox.checked = masterCheckbox.checked;
            });
            updateDeleteButton();
        }

        function updateDeleteButton() {
            const checkboxes = document.querySelectorAll('.reportCheckbox:checked');
            const bulkDeleteBtn = document.getElementById('bulkDeleteBtn');
            bulkDeleteBtn.disabled = checkboxes.length === 0;
            bulkDeleteBtn.textContent = checkboxes.length > 0 
                ? `Delete Selected (${checkboxes.length})` 
                : 'Delete Selected';
        }

        document.getElementById('selectAllBtn').addEventListener('click', function() {
            document.getElementById('masterCheckbox').checked = true;
            toggleAllCheckboxes(document.getElementById('masterCheckbox'));
        });

        document.getElementById('deselectAllBtn').addEventListener('click', function() {
            document.getElementById('masterCheckbox').checked = false;
            toggleAllCheckboxes(document.getElementById('masterCheckbox'));
        });

        document.getElementById('bulkDeleteForm').addEventListener('submit', function(e) {
            const checkboxes = document.querySelectorAll('.reportCheckbox:checked');
            if(checkboxes.length === 0) {
                e.preventDefault();
                alert('Please select at least one report to delete');
                return false;
            }
            return confirm('Are you sure you want to delete ' + checkboxes.length + ' report(s)? This action cannot be undone.');
        });
    </script>
</body>
</html>
