<?= $this->extend('layouts/sidebar') ?>

<?= $this->section('mainContent') ?>

<br><br>
<div class="page-header d-print-none">
    <div class="row align-items-center mb-3">
        <div class="col">
            <h2 class="page-title">
                <i class="fas fa-file-alt"></i> Manage Reports
            </h2>
            <p class="text-muted">Generate and manage system reports</p>
        </div>
</div>
</div>
<br>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Generate New Report</h3>
    </div>
    <div class="card-body">
        <form action="<?= base_url('/report/store') ?>" method="post">
            <?= csrf_field() ?>
            <div class="mb-3">
                <label class="form-label" for="report_type">Report Type:</label>
                <select name="report_type" id="report_type" class="form-select" required>
                    <option value="">-- Select --</option>
                    <option value="patient">Patient</option>
                    <option value="consultation">Consultation</option>
                    <option value="appointment">Appointment</option>
                    <option value="inventory">Inventory</option>
                    <option value="announcement">Announcement</option>
                    <option value="comprehensive">Comprehensive (All Data)</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-download"></i> Generate
            </button>
        </form>
    </div>
</div>

<!-- Reports List Section -->
<div class="card">
    <div class="card-header">

        <form method="get" action="<?= base_url('/report') ?>" class="row g-3">
            <div class="col-12">
                <div class="d-flex gap-3">
                    <div class="flex-grow-1">
                        <input type="text" name="search" class="form-control form-control-lg" placeholder="Search by report ID, type, date..." value="<?= esc(request()->getGet('search') ?? '') ?>">
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg">
                        <i class="fas fa-search"></i> Search
                    </button>
                    <?php if(request()->getGet('search')): ?>
                        <a href="<?= base_url('/report') ?>" class="btn btn-secondary btn-lg">
                            <i class="fas fa-times"></i> Clear
                        </a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col-12">
                <div class="d-flex gap-2 align-items-center">
                    <span class="text-dark fw-bold">Sort by ID:</span>
                    <div class="btn-group" role="group">
                        <a href="<?= base_url('/report?sort=asc' . (request()->getGet('search') ? '&search=' . esc(request()->getGet('search')) : '')) ?>" class="btn <?= (request()->getGet('sort') === 'asc') ? 'btn-info' : 'btn-outline-info' ?>">
                            <i class="fas fa-arrow-up"></i> Ascending
                        </a>
                        <a href="<?= base_url('/report?sort=desc' . (request()->getGet('search') ? '&search=' . esc(request()->getGet('search')) : '')) ?>" class="btn <?= (request()->getGet('sort') === 'desc' || empty(request()->getGet('sort'))) ? 'btn-info' : 'btn-outline-info' ?>">
                            <i class="fas fa-arrow-down"></i> Descending
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <form id="bulkDeleteForm" action="<?= base_url('/report/bulk-delete') ?>" method="post">
        <?= csrf_field() ?>

        <div class="card-body">
            <div class="btn-list mb-3">
                <button type="button" id="selectAllBtn" class="btn btn-sm btn-outline-primary">
                    <i class="fas fa-check-square"></i> Select All
                </button>
                <button type="button" id="deselectAllBtn" class="btn btn-sm btn-outline-secondary">
                    <i class="fas fa-square"></i> Deselect All
                </button>
                <button type="submit" id="bulkDeleteBtn" class="btn btn-sm btn-danger" disabled>
                    <i class="fas fa-trash"></i> Delete Selected
                </button>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-vcenter card-table">
                <thead>
                    <tr>
                        <th style="width: 40px;">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="masterCheckbox" onchange="toggleAllCheckboxes(this)">
                            </div>
                        </th>
                        <th>Report ID</th>
                        <th>Report Type</th>
                        <th>Generated By</th>
                        <th>Generated Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(!empty($report)): ?>
                        <?php foreach($report as $r): ?>
                            <tr>
                                <td>
                                    <div class="form-check">
                                        <input class="form-check-input reportCheckbox" type="checkbox" name="report_ids[]" value="<?= esc($r['report_id']) ?>" onchange="updateDeleteButton()">
                                    </div>
                                </td>
                                <td><span class="badge badge-primary"><?= esc($r['report_id']) ?></span></td>
                                <td><span class="badge badge-outline-secondary"><?= esc(ucfirst($r['report_type'])) ?></span></td>
                                <td><?= esc($r['generated_by']) ?></td>
                                <td><?= esc($r['generated_at']) ?></td>
                                <td>
                                    <a href="<?= base_url('/report/view/' . $r['report_id']) ?>" class="btn btn-sm btn-ghost-primary">
                                        <i class="fas fa-eye"></i> View
                                    </a>
                                    <a href="<?= base_url('/report/delete/' . $r['report_id']) ?>" class="btn btn-sm btn-ghost-danger" onclick="return confirm('Delete report #<?= esc($r['report_id']) ?>')">
                                        <i class="fas fa-trash"></i> Delete
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" class="text-center text-muted py-4">No reports found</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </form>
</div>

<script>
    function toggleAllCheckboxes(masterCheckbox) {
        const checkboxes = document.querySelectorAll('.reportCheckbox');
        checkboxes.forEach(checkbox => {
            checkbox.checked = masterCheckbox.checked;
        });
        updateDeleteButton();
    }

    function updateDeleteButton() {
        const checkboxes = document.querySelectorAll('.reportCheckbox:checked');
        const bulkDeleteBtn = document.getElementById('bulkDeleteBtn');
        bulkDeleteBtn.disabled = checkboxes.length === 0;
        bulkDeleteBtn.textContent = checkboxes.length > 0 
            ? `Delete Selected (${checkboxes.length})` 
            : 'Delete Selected';
    }

    document.getElementById('selectAllBtn').addEventListener('click', function() {
        document.getElementById('masterCheckbox').checked = true;
        toggleAllCheckboxes(document.getElementById('masterCheckbox'));
    });

    document.getElementById('deselectAllBtn').addEventListener('click', function() {
        document.getElementById('masterCheckbox').checked = false;
        toggleAllCheckboxes(document.getElementById('masterCheckbox'));
    });

    document.getElementById('bulkDeleteForm').addEventListener('submit', function(e) {
        const checkboxes = document.querySelectorAll('.reportCheckbox:checked');
        if(checkboxes.length === 0) {
            e.preventDefault();
            alert('Please select at least one report to delete');
            return false;
        }
        return confirm('Are you sure you want to delete ' + checkboxes.length + ' report(s)? This action cannot be undone.');
    });
</script>

<?= $this->endSection() ?>
