<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Reports</title>
</head>
<body>
    <h1>Manage Reports</h1>

    <h2>Generate New Report</h2>
    <form action="<?= base_url('/report/store') ?>" method="post">
        <?= csrf_field() ?>
        <label for="report_type">Report Type:</label>
        <select name="report_type" id="report_type" required>
            <option value="">-- Select --</option>
            <option value="patient">Patient</option>
            <option value="consultation">Consultation</option>
            <option value="appointment">Appointment</option>
            <option value="inventory">Inventory</option>
            <option value="announcement">Announcement</option>
            <option value="comprehensive">Comprehensive (All Data)</option>
        </select>
        <label for="file_path">File Path (optional):</label>
        <input type="text" name="file_path" id="file_path" placeholder="e.g. /reports/snapshot.csv">
        <button type="submit">Generate</button>
    </form>

    <h2>List of Reports</h2>

    <table border='1'>
        <tr>
            <th>Report ID</th>
            <th>Report Type</th>
            <th>Generated By</th>
            <th>Generated Date</th>
            <th>Actions</th>
        </tr>

        <?php if(!empty($report)): ?>

            <?php foreach($report as $r): ?>

                <tr>
                    <td><?= esc($r['report_id']) ?></td>
                    <td><?= esc(ucfirst($r['report_type'])) ?></td>
                    <td><?= esc($r['generated_by']) ?></td>
                    <td><?= esc($r['generated_at']) ?></td>

                    <td>
                        <a href="<?= base_url('/report/view/'.$r['report_id'])?>">View</a>
                        <a href="<?= base_url('/report/delete/'.$r['report_id'])?>" onclick="return confirm('Are you sure to delete report #<?= esc($r['report_id']) ?>?')">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>

        <?php else: ?>
            <tr>
                <td colspan="5">No Reports</td>
            </tr>
        <?php endif; ?>

    </table>
</body>
</html>
