<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Report</title>
</head>
<body>
    <h1>View Report</h1>
    <a href="/report">Back to Reports</a>

    <?php if(!empty($rep)): ?>
        <h2>Report Details</h2>
        <table border='1'>
            <tr>
                <th>Report ID</th>
                <td><?= $rep['report_id'] ?></td>
            </tr>
            <tr>
                <th>Report Type</th>
                <td><?= ucfirst(str_replace('_', ' ', $rep['report_type'])) ?></td>
            </tr>
            <tr>
                <th>Generated By</th>
                <td><?= $rep['generated_by'] ?></td>
            </tr>
            <tr>
                <th>Generated Date</th>
                <td><?= $rep['generated_at'] ?></td>
            </tr>
            <?php if($rep['file_path']): ?>
            <tr>
                <th>File Path</th>
                <td><?= $rep['file_path'] ?></td>
            </tr>
            <?php endif; ?>
        </table>

        <br><br>

        <?php if(!empty($report_data)): ?>

            <?php if($rep['report_type'] === 'patient'): ?>
                <?php if(!empty($report_data['patients'])): ?>
                <h2>Patient Report</h2>
                <p>Total Patients: <?= $report_data['total_patients'] ?></p>
                <table border='1'>
                    <tr>
                        <th>Patient ID</th>
                        <th>Full Name</th>
                        <th>Gender</th>
                        <th>Blood Type</th>
                        <th>Contact</th>
                        <th>Date Added</th>
                    </tr>
                    <?php foreach($report_data['patients'] as $p): ?>
                    <tr>
                        <td><?= $p['patient_id'] ?></td>
                        <td><?= $p['last_name'] . ', ' . $p['first_name'] . ' ' . $p['middle_name'] ?></td>
                        <td><?= $p['gender'] ?></td>
                        <td><?= $p['blood_type'] ?: 'N/A' ?></td>
                        <td><?= $p['contact_no'] ?: 'N/A' ?></td>
                        <td><?= $p['created_at'] ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Patient Report</h2>
                <p>No patients found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($rep['report_type'] === 'consultation'): ?>
                <?php if(!empty($report_data['consultations'])): ?>
                <h2>Consultation Report</h2>
                <p>Total Consultations: <?= $report_data['total_consultations'] ?></p>
                <table border='1'>
                    <tr>
                        <th>Consultation ID</th>
                        <th>Patient ID</th>
                        <th>Diagnosis</th>
                        <th>Treatment</th>
                        <th>Date</th>
                    </tr>
                    <?php foreach($report_data['consultations'] as $c): ?>
                    <tr>
                        <td><?= $c['consultation_id'] ?></td>
                        <td><?= $c['patient_id'] ?></td>
                        <td><?= substr($c['diagnosis'], 0, 50) ?>...</td>
                        <td><?= $c['treatment'] ?: 'N/A' ?></td>
                        <td><?= $c['consultation_date'] ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Consultation Report</h2>
                <p>No consultations found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($rep['report_type'] === 'appointment'): ?>
                <?php if(!empty($report_data['appointments'])): ?>
                <h2>Appointment Report</h2>
                <p>Total Appointments: <?= $report_data['total_appointments'] ?> | Pending: <?= count($report_data['pending']) ?> | Approved: <?= count($report_data['approved']) ?> | Completed: <?= count($report_data['completed']) ?></p>
                <table border='1'>
                    <tr>
                        <th>Appointment ID</th>
                        <th>Patient ID</th>
                        <th>Date</th>
                        <th>Purpose</th>
                        <th>Status</th>
                    </tr>
                    <?php foreach($report_data['appointments'] as $a): ?>
                    <tr>
                        <td><?= $a['appointment_id'] ?></td>
                        <td><?= $a['patient_id'] ?></td>
                        <td><?= $a['appointment_date'] ?></td>
                        <td><?= $a['purpose'] ?: 'N/A' ?></td>
                        <td><?= ucfirst($a['status']) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Appointment Report</h2>
                <p>No appointments found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($rep['report_type'] === 'inventory'): ?>
                <?php if(!empty($report_data['inventory'])): ?>
                <h2>Inventory Report</h2>
                <p>Total Items: <?= $report_data['total_items'] ?> | Low Stock Items (<5): <?= count($report_data['low_stock']) ?></p>
                <table border='1'>
                    <tr>
                        <th>Item ID</th>
                        <th>Item Name</th>
                        <th>Category</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>Expiry Date</th>
                    </tr>
                    <?php foreach($report_data['inventory'] as $i): ?>
                    <tr>
                        <td><?= $i['item_id'] ?></td>
                        <td><?= $i['item_name'] ?></td>
                        <td><?= ucfirst($i['category']) ?></td>
                        <td><?= $i['quantity'] ?></td>
                        <td><?= $i['unit'] ?: 'N/A' ?></td>
                        <td><?= $i['expiry_date'] ?: 'N/A' ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Inventory Report</h2>
                <p>No inventory items found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($rep['report_type'] === 'announcement'): ?>
                <?php if(!empty($report_data['announcements'])): ?>
                <h2>Announcement Report</h2>
                <p>Total Announcements: <?= $report_data['total_announcements'] ?></p>
                <table border='1'>
                    <tr>
                        <th>Announcement ID</th>
                        <th>Title</th>
                        <th>Posted By</th>
                        <th>Posted Date</th>
                        <th>Posted Until</th>
                    </tr>
                    <?php foreach($report_data['announcements'] as $an): ?>
                    <tr>
                        <td><?= $an['announcement_id'] ?></td>
                        <td><?= $an['title'] ?></td>
                        <td><?= $an['posted_by'] ?></td>
                        <td><?= $an['posted_at'] ?></td>
                        <td><?= $an['posted_until'] ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Announcement Report</h2>
                <p>No announcements found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($rep['report_type'] === 'comprehensive'): ?>
                <?php if(!empty($report_data['summary'])): ?>
                <h2>Comprehensive Report</h2>
                <p>Total Patients: <?= $report_data['summary']['total_patients'] ?> | Total Consultations: <?= $report_data['summary']['total_consultations'] ?> | Total Appointments: <?= $report_data['summary']['total_appointments'] ?> | Total Inventory Items: <?= $report_data['summary']['total_inventory_items'] ?> | Total Announcements: <?= $report_data['summary']['total_announcements'] ?></p>

                <h3>Patients</h3>
                <?php if(!empty($report_data['patients'])): ?>
                <table border='1'>
                    <tr>
                        <th>Patient ID</th>
                        <th>Full Name</th>
                        <th>Gender</th>
                        <th>Contact</th>
                    </tr>
                    <?php foreach($report_data['patients'] as $p): ?>
                    <tr>
                        <td><?= $p['patient_id'] ?></td>
                        <td><?= $p['last_name'] . ', ' . $p['first_name'] ?></td>
                        <td><?= $p['gender'] ?></td>
                        <td><?= $p['contact_no'] ?: 'N/A' ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <p>No patients found</p>
                <?php endif; ?>

                <h3>Recent Consultations</h3>
                <?php if(!empty($report_data['consultations'])): ?>
                <table border='1'>
                    <tr>
                        <th>Consultation ID</th>
                        <th>Patient ID</th>
                        <th>Diagnosis</th>
                        <th>Date</th>
                    </tr>
                    <?php $count = 0; foreach($report_data['consultations'] as $c): if($count++ < 10): ?>
                    <tr>
                        <td><?= $c['consultation_id'] ?></td>
                        <td><?= $c['patient_id'] ?></td>
                        <td><?= substr($c['diagnosis'], 0, 50) ?>...</td>
                        <td><?= $c['consultation_date'] ?></td>
                    </tr>
                    <?php endif; endforeach; ?>
                </table>
                <?php else: ?>
                <p>No consultations found</p>
                <?php endif; ?>

                <h3>Appointments Overview</h3>
                <?php if(!empty($report_data['appointments'])): ?>
                <table border='1'>
                    <tr>
                        <th>Appointment ID</th>
                        <th>Patient ID</th>
                        <th>Status</th>
                        <th>Date</th>
                    </tr>
                    <?php $count = 0; foreach($report_data['appointments'] as $a): if($count++ < 10): ?>
                    <tr>
                        <td><?= $a['appointment_id'] ?></td>
                        <td><?= $a['patient_id'] ?></td>
                        <td><?= ucfirst($a['status']) ?></td>
                        <td><?= $a['appointment_date'] ?></td>
                    </tr>
                    <?php endif; endforeach; ?>
                </table>
                <?php else: ?>
                <p>No appointments found</p>
                <?php endif; ?>
                <?php else: ?>
                <h2>Comprehensive Report</h2>
                <p>No data available for comprehensive report</p>
                <?php endif; ?>
            <?php endif; ?>

        <?php endif; ?>

        <br><br>
        <button><a href="<?= base_url('/report/export/'.$rep['report_id']) ?>">Export as CSV</a></button>
        <a href="<?= base_url('/report/delete/'.$rep['report_id']) ?>" onclick="return confirm('Are you sure?')">Delete Report</a>

    <?php else: ?>
        <p>Report not found</p>
    <?php endif; ?>
</body>
</html>
