<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Report</title>
</head>
<body>
    <h1>View Report</h1>

    <a href="/report">Back to Reports</a>

    <h2>Report Details</h2>

    <?php if(!empty($rep)): ?>
        <table border='1'>
            <tr>
                <th>Field</th>
                <th>Value</th>
            </tr>
            <tr>
                <td>Report ID</td>
                <td><?= $rep['report_id'] ?></td>
            </tr>
            <tr>
                <td>Report Type</td>
                <td><?= ucfirst($rep['report_type']) ?></td>
            </tr>
            <tr>
                <td>Generated By</td>
                <td><?= $rep['generated_by'] ?></td>
            </tr>
            <tr>
                <td>Generated Date</td>
                <td><?= $rep['generated_at'] ?></td>
            </tr>
            <tr>
                <td>File Path</td>
                <td><?= $rep['file_path'] ?: 'N/A' ?></td>
            </tr>
        </table>

        <br><br>
        <a href="<?= base_url('/report/delete/'.$rep['report_id']) ?>" onclick="return confirm('Are you sure?')">Delete</a>

    <?php else: ?>
        <p>Report not found</p>
    <?php endif; ?>
</body>
</html>
