<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Report</title>
</head>
<body>
    <h1>View Report</h1>
    <a href="/report">Back to Reports</a>

    <?php if(!empty($rep)): ?>
        <h2>Report Details</h2>
        <table border='1'>
            <tr>
                <th>Report ID</th>
                <td><?= esc($rep['report_id']) ?></td>
            </tr>
            <tr>
                <th>Report Type</th>
                <td><?= esc(ucfirst(str_replace('_', ' ', $rep['report_type']))) ?></td>
            </tr>
            <tr>
                <th>Generated By</th>
                <td><?= esc($rep['generated_by']) ?></td>
            </tr>
            <tr>
                <th>Generated Date</th>
                <td><?= esc($rep['generated_at']) ?></td>
            </tr>
            <?php if($rep['file_path']): ?>
            <tr>
                <th>File Path</th>
                <td><?= esc($rep['file_path']) ?></td>
            </tr>
            <?php endif; ?>
        </table>

        <br><br>

        <?php 
        $report_type = strtolower(trim($rep['report_type']));
        // If stored report_type is blank, show a chooser to let the user select which report type to render.
        // Ensure all expected keys exist with defaults
        $report_data = array_merge([
            'patients' => [],
            'consultations' => [],
            'appointments' => [],
            'inventory' => [],
            'announcements' => [],
            'pending' => [],
            'approved' => [],
            'completed' => [],
            'low_stock' => [],
            'summary' => [],
            'total_patients' => 0,
            'total_consultations' => 0,
            'total_appointments' => 0,
            'total_items' => 0,
            'total_announcements' => 0,
        ], $report_data ?? []);
        ?>

        <?php if(empty($report_type)): ?>
            <h2>Report type not set</h2>
            <p>This report was created before report types were required. Choose which report type you want this record to represent (this will update the report row):</p>
            <form action="<?= base_url('/report/set_report_type/'.$rep['report_id']) ?>" method="post">
                <?= csrf_field() ?>
                <label for="report_type">Report Type:</label>
                <select name="report_type" id="report_type" required>
                    <option value="">-- Select --</option>
                    <option value="patient">Patient</option>
                    <option value="consultation">Consultation</option>
                    <option value="appointment">Appointment</option>
                    <option value="inventory">Inventory</option>
                    <option value="announcement">Announcement</option>
                    <option value="comprehensive">Comprehensive (All Data)</option>
                </select>
                <button type="submit">Set and View</button>
            </form>

        <?php elseif(!empty($report_data)): ?>

            <?php if($report_type === 'patient'): ?>
                <?php if(!empty($report_data['patients'])): ?>
                <h2>Patient Report</h2>
                <p>Total Patients: <?= $report_data['total_patients'] ?></p>
                <table border='1'>
                    <tr>
                        <th>Patient ID</th>
                        <th>Full Name</th>
                        <th>Gender</th>
                        <th>Blood Type</th>
                        <th>Contact</th>
                        <th>Date Added</th>
                    </tr>
                    <?php foreach($report_data['patients'] as $p): ?>
                    <tr>
                        <td><?= esc($p['patient_id']) ?></td>
                        <td><?= esc($p['last_name']) . ', ' . esc($p['first_name']) . ' ' . esc($p['middle_name']) ?></td>
                        <td><?= esc($p['gender']) ?></td>
                        <td><?= esc($p['blood_type'] ?: 'N/A') ?></td>
                        <td><?= esc($p['contact_no'] ?: 'N/A') ?></td>
                        <td><?= esc($p['created_at']) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Patient Report</h2>
                <p>No patients found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($report_type === 'consultation'): ?>
                <?php if(!empty($report_data['consultations'])): ?>
                <h2>Consultation Report</h2>
                <p>Total Consultations: <?= esc($report_data['total_consultations']) ?></p>
                <table border='1'>
                    <tr>
                        <th>Consultation ID</th>
                        <th>Patient ID</th>
                        <th>Diagnosis</th>
                        <th>Treatment</th>
                        <th>Date</th>
                    </tr>
                    <?php foreach($report_data['consultations'] as $c): ?>
                    <tr>
                        <td><?= esc($c['consultation_id']) ?></td>
                        <td><?= esc($c['patient_id']) ?></td>
                        <td><?= esc($c['diagnosis']) ?></td>
                        <td><?= esc($c['treatment'] ?: 'N/A') ?></td>
                        <td><?= esc($c['consultation_date']) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Consultation Report</h2>
                <p>No consultations found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($report_type === 'appointment'): ?>
                <?php if(!empty($report_data['appointments'])): ?>
                <h2>Appointment Report</h2>
                <p>Total Appointments: <?= esc($report_data['total_appointments']) ?> | Pending: <?= esc(count($report_data['pending'])) ?> | Approved: <?= esc(count($report_data['approved'])) ?> | Completed: <?= esc(count($report_data['completed'])) ?></p>
                <table border='1'>
                    <tr>
                        <th>Appointment ID</th>
                        <th>Patient ID</th>
                        <th>Date</th>
                        <th>Purpose</th>
                        <th>Status</th>
                    </tr>
                    <?php foreach($report_data['appointments'] as $a): ?>
                    <tr>
                        <td><?= esc($a['appointment_id']) ?></td>
                        <td><?= esc($a['patient_id']) ?></td>
                        <td><?= esc($a['appointment_date']) ?></td>
                        <td><?= esc($a['purpose'] ?: 'N/A') ?></td>
                        <td><?= esc(ucfirst($a['status'])) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Appointment Report</h2>
                <p>No appointments found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($report_type === 'inventory'): ?>
                <?php if(!empty($report_data['inventory'])): ?>
                <h2>Inventory Report</h2>
                <p>Total Items: <?= $report_data['total_items'] ?> | Low Stock Items (<5): <?= count($report_data['low_stock']) ?></p>
                <table border='1'>
                    <tr>
                        <th>Item ID</th>
                        <th>Item Name</th>
                        <th>Category</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>Expiry Date</th>
                    </tr>
                    <?php foreach($report_data['inventory'] as $i): ?>
                    <tr>
                        <td><?= esc($i['item_id']) ?></td>
                        <td><?= esc($i['item_name']) ?></td>
                        <td><?= esc(ucfirst($i['category'])) ?></td>
                        <td><?= esc($i['quantity']) ?></td>
                        <td><?= esc($i['unit'] ?: 'N/A') ?></td>
                        <td><?= esc($i['expiry_date'] ?: 'N/A') ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Inventory Report</h2>
                <p>No inventory items found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($report_type === 'announcement'): ?>
                <?php if(!empty($report_data['announcements'])): ?>
                <h2>Announcement Report</h2>
                <p>Total Announcements: <?= esc($report_data['total_announcements']) ?></p>
                <table border='1'>
                    <tr>
                        <th>Announcement ID</th>
                        <th>Title</th>
                        <th>Posted By</th>
                        <th>Posted Date</th>
                        <th>Posted Until</th>
                    </tr>
                    <?php foreach($report_data['announcements'] as $an): ?>
                    <tr>
                        <td><?= esc($an['announcement_id']) ?></td>
                        <td><?= esc($an['title']) ?></td>
                        <td><?= esc($an['posted_by']) ?></td>
                        <td><?= esc($an['posted_at']) ?></td>
                        <td><?= esc($an['posted_until']) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <h2>Announcement Report</h2>
                <p>No announcements found in the system</p>
                <?php endif; ?>
            <?php endif; ?>

            <?php if($report_type === 'comprehensive'): ?>
                <?php if(!empty($report_data['summary'])): ?>
                <h2>Comprehensive Report</h2>
                <p>Total Patients: <?= $report_data['summary']['total_patients'] ?> | Total Consultations: <?= $report_data['summary']['total_consultations'] ?> | Total Appointments: <?= $report_data['summary']['total_appointments'] ?> | Total Inventory Items: <?= $report_data['summary']['total_inventory_items'] ?> | Total Announcements: <?= $report_data['summary']['total_announcements'] ?></p>

                <h3>Patients</h3>
                <?php if(!empty($report_data['patients'])): ?>
                <table border='1'>
                    <tr>
                        <th>Patient ID</th>
                        <th>Full Name</th>
                        <th>Gender</th>
                        <th>Contact</th>
                    </tr>
                    <?php foreach($report_data['patients'] as $p): ?>
                    <tr>
                        <td><?= esc($p['patient_id']) ?></td>
                        <td><?= esc($p['last_name']) . ', ' . esc($p['first_name']) ?></td>
                        <td><?= esc($p['gender']) ?></td>
                        <td><?= esc($p['contact_no'] ?: 'N/A') ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <p>No patients found</p>
                <?php endif; ?>

                <h3>Consultations</h3>
                <?php if(!empty($report_data['consultations'])): ?>
                <table border='1'>
                    <tr>
                        <th>Consultation ID</th>
                        <th>Appointment ID</th>
                        <th>Patient ID</th>
                        <th>Diagnosis</th>
                        <th>Treatment</th>
                        <th>Date</th>
                    </tr>
                    <?php foreach($report_data['consultations'] as $c): ?>
                    <tr>
                        <td><?= esc($c['consultation_id']) ?></td>
                        <td><?= esc($c['appointment_id'] ?? 'N/A') ?></td>
                        <td><?= esc($c['patient_id']) ?></td>
                        <td><?= esc($c['diagnosis']) ?></td>
                        <td><?= esc($c['treatment'] ?: 'N/A') ?></td>
                        <td><?= esc($c['consultation_date']) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <p>No consultations found</p>
                <?php endif; ?>

                <h3>Appointments</h3>
                <?php if(!empty($report_data['appointments'])): ?>
                <table border='1'>
                    <tr>
                        <th>Appointment ID</th>
                        <th>Patient ID</th>
                        <th>Date</th>
                        <th>Purpose</th>
                        <th>Status</th>
                        <th>Remarks</th>
                    </tr>
                    <?php foreach($report_data['appointments'] as $a): ?>
                    <tr>
                        <td><?= esc($a['appointment_id']) ?></td>
                        <td><?= esc($a['patient_id']) ?></td>
                        <td><?= esc($a['appointment_date']) ?></td>
                        <td><?= esc($a['purpose'] ?: 'N/A') ?></td>
                        <td><?= esc(ucfirst($a['status'])) ?></td>
                        <td><?= esc($a['remarks'] ?? 'N/A') ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else: ?>
                <p>No appointments found</p>
                <?php endif; ?>
                <?php else: ?>
                <h2>Comprehensive Report</h2>
                <p>No data available for comprehensive report</p>
                <?php endif; ?>
            <?php endif; ?>

        <?php endif; ?>

        <br><br>
        <div style="display:flex; gap:8px; align-items:center;">
            <a class="btn" href="<?= base_url('/report/export/'.$rep['report_id']) ?>">Export CSV</a>
            <a class="btn" href="<?= base_url('/report/export/'.$rep['report_id']) ?>?format=xlsx">Export Excel</a>
            <a class="btn" href="<?= base_url('/report/export/'.$rep['report_id']) ?>?format=pdf">Export PDF</a>
            <a class="btn btn-danger" href="<?= base_url('/report/delete/'.$rep['report_id']) ?>" onclick="return confirm('Are you sure you want to delete this report?')">Delete Report</a>
        </div>

    <?php else: ?>
        <p>Report not found</p>
    <?php endif; ?>
</body>
</html>
